name: AI Code Review

on:
  push:
    branches:
      - main # 或您希望监控的其他分支
      - master

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # 根据您的项目需要选择 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Run AI Code Review
        run: |
          # 在这里调用您的 AI 代码审查工具
          # 例如，您可以使用一个自定义的脚本或工具
          echo "运行 AI 代码审查工具"
